
exam1:exam1.o address.o calculator.o date_time.o input.o output.o utilities.o
	g++ -o exam1 exam1.o address.o calculator.o date_time.o input.o output.o utilities.o

exam2:exam2.o address.o calculator.o date_time.o input.o output.o utilities.o
	g++ -o exam2 exam2.o address.o calculator.o date_time.o input.o output.o utilities.o

exam3:exam3.o address.o calculator.o date_time.o input.o output.o utilities.o
	g++ -o exam3 exam3.o address.o calculator.o date_time.o input.o output.o utilities.o

exam4:exam4.o address.o calculator.o date_time.o input.o output.o utilities.o
	g++ -o exam4 exam4.o address.o calculator.o date_time.o input.o output.o utilities.o

exam5:exam5.o address.o calculator.o date_time.o input.o output.o utilities.o
	g++ -o exam5 exam5.o address.o calculator.o date_time.o input.o output.o utilities.o

exam1.o: exam1.cpp
	g++ -c exam1.cpp

exam2.o: exam2.cpp
	g++ -c exam2.cpp

exam3.o: exam3.cpp
	g++ -c exam3.cpp

exam4.o: exam4.cpp
	g++ -c exam4.cpp

exam5.o: exam5.cpp
	g++ -c exam5.cpp

address.o: address.cpp
	g++ -c address.cpp

calculator.o: calculator.cpp
	g++ -c calculator.cpp

date_time.o: date_time.cpp
	g++ -c date_time.cpp

input.o: input.cpp
	g++ -c input.cpp

output.o: output.cpp
	g++ -c output.cpp

utilities.o: utilities.cpp
	g++ -c utilities.cpp

generator: generator.o
	g++ -o generator generator.o

generator.o: generator.cpp
	g++ -c generator.cpp
clean:
	$(RM) exam1
	$(RM) exam2
	$(RM) exam3
	$(RM) exam4